export interface TaskInterface {
    id: string,
    projectId: string,
    employeeId: string,
    name: string,
    description: string,
    startAt: Date,
    endAt: Date | null,
    dueDate: Date | null,
    tag1: number,
    tag2: number,
    tag3: number,
    status: number,
    completed: boolean,
    priority: number,
    taskPoints: number,
}

export const EmptyTask: TaskInterface = {
    id: '',
    projectId: '',
    employeeId: '',
    name: '',
    description: '',
    startAt: new Date(),
    endAt: null,
    dueDate: null,
    tag1: 0,
    tag2: 0,
    tag3: 0,
    status: 0,
    completed: false,
    priority: 0,
    taskPoints: 0,
}
