export { LoginComponent } from '@modules/authentication/pages/login/login.component'
export { SignupComponent } from '@modules/authentication/components/signup/signup.component'
export { SigninComponent } from '@modules/authentication/components/signin/signin.component'
export { AuthenticationRoutingModule } from '@modules/authentication/authentication-routing.module'
export { AuthenticationModule } from '@modules/authentication/authentication.module'
export { Credentials } from '@modules/authentication/interfaces/credentials.interface'
export { Registration } from '@modules/authentication/interfaces/registration.interface'
export { passwordsMustMatchValidator } from '@modules/authentication/shared/passwords-match.validator'